# Generated by Django 2.2.6 on 2020-04-07 15:53

from django.db import migrations, models
import files.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=files.models.archive_path)),
                ('name', models.CharField(max_length=200)),
                ('hash', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=files.models.file_path)),
                ('name', models.CharField(max_length=200)),
                ('hash', models.CharField(max_length=30)),
            ],
        ),
    ]
